---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-hello

bases:
  - ../../base

patches:
  - path: replicas.yaml
    target:
      kind: Deployment
  - path: image.yaml
    target:
      kind: Deployment
