---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-hello

bases:
  - ../../base

images:
  - name: nginxdemos/hello
    newName: nginxdemos/hello
    newTag: latest

patches:
  - path: replicas.yaml
    target:
      kind: Deployment
