---
apiVersion: v1
kind: Service
metadata:
  name: nginx-hello-service
  namespace: nginx-hello
spec:
  type: NodePort
  selector:
    app: nginx-hello
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30222
