apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello
  labels:
    app: nginx-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-hello
  template:
    metadata:
      labels:
        app: nginx-hello
    spec:
      containers:
      - name: nginx-hello
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-hello-service
spec:
  type: NodePort
  selector:
    app: nginx-hello
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30222

# if curl http://localhost:30222 doesn't work in WSL, try:
# kubectl port-forward service/nginx-hello 8080:80
